# .github/workflows/ci-scripts-build.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

# This is YAML - indentation levels are crucial

name: PVXS

# Trigger on pushes and PRs to any branch
on:
  push:
    paths-ignore:
      - .appveyor.yml
  pull_request:

env:
  SETUP_PATH: .ci-local
  CMP: gcc
  _PVXS_ABORT_ON_CRIT: 1
  PVXS_LOG: pvxs.*=WARN

jobs:
  native-epics:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    # Set environment variables from matrix parameters
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      WINE: ${{ matrix.wine }}
      RTEMS: ${{ matrix.rtems }}
      RTEMS_TARGET: ${{ matrix.rtems_target }}
      LIBEVENT_TAG: ${{ matrix.libevent }}
      TEST: ${{ matrix.test }}
      EXTRA: ${{ matrix.extra }}
      VV: "1"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Native Linux (WError)
            os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "7.0"
            extra: "CMD_CPPFLAGS=-Werror"

          - name: Cross mingw64 DLL
            os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "7.0"
            wine: "64"

          - name: Cross mingw64 static
            os: ubuntu-20.04
            cmp: gcc
            configuration: static
            base: "7.0"
            wine: "64"

          - name: RTEMS5
            os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "7.0"
            rtems: "5"
            rtems_target: RTEMS-pc686-qemu
 
          - name: Native Linux with clang
            os: ubuntu-20.04
            cmp: clang
            configuration: default
            base: "7.0"

          - name: Native Linux with libevent stable
            os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "7.0"
            libevent: "release-2.0.22-stable"

          - name: Native Linux with 3.15
            os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "3.15"

          - name: Native Linux with 3.14
            os: ubuntu-20.04
            cmp: gcc
            configuration: default
            base: "3.14"

          - name: OSX
            os: macos-latest
            cmp: clang
            configuration: default
            base: "7.0"

          - name: vs2019 DLL
            os: windows-2019
            cmp: vs2019
            configuration: default
            base: "7.0"

          - name: vs2019 static
            os: windows-2019
            cmp: vs2019
            configuration: static
            base: "7.0"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: "apt-get install"
      run: |
        sudo apt-get update
        sudo apt-get -y install g++-mingw-w64-x86-64 cmake gdb qemu-system-x86
      if: runner.os == 'Linux'
    - name: Automatic core dumper analysis
      uses: mdavidsaver/ci-core-dumper@master
    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare
    - name: Build libevent
      run: python .ci/cue.py exec python .ci-local/libevent.py
    - name: Build main module
      run: python .ci/cue.py build
    - name: Host info
      run: python .ci/cue.py --add-path "{TOP}/bin/{EPICS_HOST_ARCH}" --add-path "{TOP}/bundle/usr/{EPICS_HOST_ARCH}/lib" exec pvxinfo -D
    - name: Run main module tests
      run: python -m ci_core_dumper exec python .ci/cue.py --add-path "{TOP}/bundle/usr/{EPICS_HOST_ARCH}/lib" test
    - name: Collect and show test results
      run: python .ci/cue.py test-results
    - name: CDT Check
      run: ./.ci-local/cdt-check.sh
      if: runner.os == 'Linux'
    - name: Upload tapfiles Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: tapfiles ${{ matrix.name }}
        path: '**/O.*/*.tap'

  docker-epics:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      BASE: ${{ matrix.base }}
      WINE: ${{ matrix.wine }}
      LIBEVENT_TAG: ${{ matrix.libevent }}
      EXTRA: ${{ matrix.extra }}
      VV: "1"
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux centos 7
            image: centos:7
            cmp: gcc
            configuration: default
            base: "7.0"

          - name: Linux centos 8
            image: centos:8
            cmp: gcc
            configuration: default
            base: "7.0"

          - name: Linux fedora 34
            image: fedora:34
            cmp: gcc
            configuration: default
            base: "7.0"

    steps:
    - name: "Build newer Git"
      # actions/checkout@v2 wants git >=2.18
      # centos:7 has 1.8
      if: matrix.image=='centos:7'
      run: |
        yum -y install curl make gcc curl-devel expat-devel gettext-devel openssl-devel zlib-devel perl-ExtUtils-MakeMaker
        curl https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.29.0.tar.gz | tar -xz
        cd git-*
        make -j2 prefix=/usr/local all
        make prefix=/usr/local install
        cd ..
        rm -rf git-*
        type -a git
        git --version
    - name: "Redhat setup"
      run: |
        dnfyum() {
            dnf -y "$@" || yum -y "$@"
            return $?
        }
        dnfyum install python3 gdb make perl gcc-c++ glibc-devel readline-devel ncurses-devel perl-devel libevent-devel
        git --version || dnfyum install git
        # rather than just bite the bullet and link python3 -> python,
        # people would rather just break all existing scripts...
        [ -e /usr/bin/python ] || ln -sf /usr/bin/python3 /usr/bin/python
        python --version
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Automatic core dumper analysis
      uses: mdavidsaver/ci-core-dumper@master
    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare
    - name: Build main module
      run: python .ci/cue.py build
    - name: Host info
      run: python .ci/cue.py --add-path "{TOP}/bin/{EPICS_HOST_ARCH}" exec pvxinfo -D
    - name: Run main module tests
      run: python -m ci_core_dumper exec python .ci/cue.py test
    - name: Collect and show test results
      run: python .ci/cue.py test-results
    - name: CDT Check
      run: ./.ci-local/cdt-check.sh
    - name: Upload tapfiles Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: tapfiles ${{ matrix.name }}
        path: '**/O.*/*.tap'

  native-py:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      PRE:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux64 test
            os: ubuntu-latest
            python: "3.5"

          # OSX py builds
          - name: osx 2.7 intel
            os: macos-latest
            python: "2.7"
            piparch: macosx_10_9_intel

          - name: osx 3.6 intel
            os: macos-latest
            python: "3.6"
            piparch: macosx_10_9_intel

          - name: osx 3.7 intel
            os: macos-latest
            python: "3.7"
            piparch: macosx_10_9_intel

          - name: osx 3.8 intel
            os: macos-latest
            python: "3.8"
            piparch: macosx_10_9_intel

          - name: osx 3.9 intel
            os: macos-latest
            python: "3.9"
            piparch: macosx_10_9_intel

          # Windows py builds

          ## missing Microsoft Visual C++ 9.0
          #- os: windows-latest
          #  python: "2.7"
          #  piparch: win_amd64

          - name: win64 3.5
            os: windows-latest
            python: "3.5"
            piparch: win_amd64

          - name: win64 3.6
            os: windows-latest
            python: "3.6"
            piparch: win_amd64

          - name: win64 3.7
            os: windows-latest
            python: "3.7"
            piparch: win_amd64

          - name: win64 3.8
            os: windows-latest
            python: "3.8"
            piparch: win_amd64

          - name: win64 3.9
            os: windows-latest
            python: "3.9"
            piparch: win_amd64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Automatic core dumper analysis
        uses: mdavidsaver/ci-core-dumper@master


      - name: Setup native python
        if: matrix.python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          #architecture: x64

      - name: Prepare
        shell: bash
        run: |
          python -m pip install -U pip
          python -m pip install twine
          python --version
          python -m pip --version
          python -m twine -h

          python -m pip install setuptools wheel nose2
          python -m pip install $PRE setuptools_dso>=2.1a1 epicscorelibs>=7.0.3.99.2.0a1

      - name: Source
        run: python setup.py sdist --formats=gztar

      - name: Wheel
        shell: bash
        run: python -m pip wheel -v -w dist dist/pvxslibs-*.tar.gz

      - name: Test Wheel
        run: |
          cd dist
          python -m pip install pvxslibs-*.whl
          python -m nose2 pvxslibs

      - name: List Artifacts
        run: ls dist/*

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: epicscorelibs
          path: dist/*

  docker-py:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      PRE:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux py builds x64
          - name: linux 2.7 amd64
            os: ubuntu-latest
            pyver: cp27-cp27m
            manylinux: manylinux1
            arch: x86_64

          # Linux py builds x32
          - name: linux 2.7 i686
            os: ubuntu-latest
            pyver: cp27-cp27m
            manylinux: manylinux1
            arch: x86_64
            pre: linux32

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup native python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python || '3.7' }}
          #architecture: x64

      - name: Native Prep/Info
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          which python
          python --version
          python -m pip --version
          python -m twine -h
          python ./gha-set-pre.py

      - name: PY Source
        run: |
          echo "PRE=$PRE"
          python -m pip install setuptools wheel nose2
          python -m pip install $PRE setuptools-dso
          python setup.py sdist --formats=gztar
          ls dist/*

      - name: Docker PY build
        if: matrix.pyver && !matrix.source
        run: |
          # can't use GHA native docker support since GHA magic binaries need .so absent from old manylinux images :(
          cat <<EOF > runit.sh
          #!/bin/sh
          set -e -x
          cd /io
          [ -d dist ]
          ls dist/*
          export PATH="/opt/python/${{ matrix.pyver }}/bin:\$PATH"
          export SETUPTOOLS_DSO_MANYLINUX=${{ matrix.manylinux }}
          which python
          python -m pip install -U pip
          python -m pip install nose2

          python -m pip wheel -v -w dist dist/pvxslibs-*.tar.gz

          cd dist
          python -m pip install pvxslibs-*.whl
          python -m nose2 pvxslibs
          cd ..

          EOF
          cat runit.sh
          chmod +x runit.sh
          docker pull quay.io/pypa/${{ matrix.piparch }}
          docker run --rm -v `pwd`:/io quay.io/pypa/${{ matrix.manylinux }}_${{ matrix.arch }} ${{ matrix.pre }} /io/runit.sh

      - name: List Artifacts
        run: ls dist/*

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: epicscorelibs
          path: dist/*
